name: Java CI with Maven
'on':
  push:
    branches:
      - master
jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: |
         cd springdoc-openapi-spring-boot-2-webmvc
         mvn test


  deploy:
    runs-on: ubuntu-latest
    name: Deploy the JAR file to the remote server
    needs: unittest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate the package using Maven
        run: |
         cd springdoc-openapi-spring-boot-2-webmvc
         mvn package

      - name: Deploy to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: springdoc-openapi-spring-boot-2-webmvc/target/springdoc-openapi-spring-boot-2-webmvc-3.1.6-SNAPSHOT.jar
          remote: /home/ubuntu/springdoc-openapi-spring-boot-2-webmvc-3.1.6-SNAPSHOT.jar
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.SSH_USER }}'
          privateKey: '${{ secrets.PRIVATE_KEY }}'

      - name: Run script on remote server
        if: always()
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/ubuntu && java -jar springdoc-openapi-spring-boot-2-webmvc-3.1.6-SNAPSHOT.jar &
          host: '${{ secrets.HOST }}'
          user: '${{ secrets.SSH_USER }}'
          key: '${{ secrets.PRIVATE_KEY }}'
          args: '-tt'
